### ISSUE TITLE
AssetManager::updateAssets - extension/filename string is assigned to std::string

### ISSUE THREAD

**Issue by herodees** [RedE01/glGame#1]
On windows platform path chartype is wchar_t. You need to convert extension string to propper format:
`std::string extension = entry.path().extension().string(), filename = entry.path().filename().string(), pathStr = entry.path().string();`
or better
`std::string extension = entry.path().extension().u8string(), filename = entry.path().filename().u8string(), pathStr = entry.path().u8string();`

**Comment by edvinsternvik** [comment]
Thank you, it should be fixed now.
